const VERTICAL_SYMBOLS = ['1', '2', '3', '4', '5', '6', '7', '8'];
const VERTICAL_SYMBOLS_REVERSE = [...VERTICAL_SYMBOLS].reverse();
const HORIZONTAL_SYMBOLS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'];
const HORIZONTAL_SYMBOLS_REVERSE = [...HORIZONTAL_SYMBOLS].reverse();

export { VERTICAL_SYMBOLS, VERTICAL_SYMBOLS_REVERSE, HORIZONTAL_SYMBOLS, HORIZONTAL_SYMBOLS_REVERSE };
