const BREAKPOINT_MIN = 320;
const BREAKPOINT_XS = 375;
const BREAKPOINT_XM = 540;
const BREAKPOINT_SM = 768;
const BREAKPOINT_MD = 1024;
const BREAKPOINT_LG = 1280;
const BREAKPOINT_XL = 1440;
const BREAKPOINT_XXL = 1920;

export {
  BREAKPOINT_MIN,
  BREAKPOINT_XS,
  BREAKPOINT_XM,
  BREAKPOINT_SM,
  BREAKPOINT_MD,
  BREAKPOINT_LG,
  BREAKPOINT_XL,
  BREAKPOINT_XXL,
};
